language: objective-c
osx_image: xcode8
env:
  - DESTINATION="OS=10.0,name=iPhone 6s" SCHEME="GooglePlacesRow" SDK=iphonesimulator10.0

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project GooglePlacesRow.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
